### PR TITLE
Propose a Logo

### PR DESCRIPTION
**Pull request by kellertuer**
I finally found the trick to finish my idea – the arrows now align nicely with the lines and we have nice and pointy arrows. Here is my proposal and this PR directly also adds this to the docs.
Instead of geodesics we here have rotations happening, in the center I put the group operation, we could also put a dot for the group action, but I thought the circ looks a bit nicer.

logo-dark
logo

### CODE REVIEW

**Comment by mateuszbaran** [comment]
Why do the Julia colors seem different here than in the Manifolds.jl logo? And I think the circle makes the logo a bit too busy. Otherwise it looks nice.

**Comment by kellertuer** [comment]
I don‘t know. It is nearly the same code (definitely the same colours), just that geodesics had to be shortened a bit to fix the arrow alignment.

Sure I can create here real quickly sketches without the operation, that is also fine with me (updating all logos I‘ll do in the end then)

logo-dark
logo

**Comment by kellertuer** [comment]
You are actually right, it looks even a bit calmer and nicer without the group action. I still have to update the favicon tomorrow then. But the docs logo should be updated already.

**Comment by kellertuer** [comment]
Found it! The patches were only at 75% opacity and hence not as bright as before (maybe I did that for Diff?) fixed now and also generated the logo with text for the readme.

**Comment by mateuszbaran** [comment]
Great! Now the logo looks fine IMO.

**Review by mateuszbaran — APPROVED** [review]

**Comment by kellertuer** [comment]
I hope I did the readme correctly so it will look fancy once we merge this, let's see.

**Pull request merged**
